### ISSUE TITLE
Add support for SiliconFlow API

### ISSUE THREAD

**Issue by xbot** [Undertone0809/gcop#192]
## 🚀 Feature Request

Support SiliconFlow API.

## 🔈 Motivation

SiliconFlow provides 20,000,000 free tokens for the DeepSeek model.

**Comment by warvyvr** [comment]
Hi,
  just notice SiliconFlow supports OpenAI interface, you can directly config in config file like:
```yaml
model:
  model_name: openai/<your model name>
  api_key:<your api key>
  api_base: https://api.siliconflow.cn/v1
```
